export const categories = [
  {
    id: 1, // Ensure unique IDs
    name: "Food", // Short and clear
    image: require("../assets/images/categories/food.png"),
  },
  {
    id: 2,
    name: "Groceries", // Short and clear
    image: require("../assets/images/categories/groceries.png"),
  },
  {
    id: 3,
    name: "Pharmacy", // Short and clear
    image: require("../assets/images/categories/pharmacy.png"),
  },
  // --- Future Categories (Commented out for now) ---
  // {
  //   id: 4,
  //   name: "General", // Short for General Merchandise
  //   image: require("../assets/images/categories/general_icon.png"),
  // },
  // {
  //   id: 5,
  //   name: "Appliances", // Short and clear
  //   image: require("../assets/images/categories/appliances_icon.png"),
  // },
  // {
  //   id: 6,
  //   name: "Furniture", // Short and clear
  //   image: require("../assets/images/categories/furniture_icon.png"),
  // },
  // {
  //   id: 7,
  //   name: "Fashion", // Short for Clothing/Fashion
  //   image: require("../assets/images/categories/fashion_icon.png"),
  // },
];

export const restaurants = [
  {
    id: 1,
    name: "Luigi's Restaurant",
    image: require("../assets/images/resto.jpg"),
    description: "Italian and Mediterranean cuisine with a cozy atmosphere.",
    rating: 4.6,
    address: "23 Kairaba Avenue, Banjul",
    categories: ["Italian", "Mediterranean"],
    openingHours: "11:00 AM - 10:00 PM",
    reviewsCount: 120,
    freeDelivery: true,
  },
  {
    id: 2,
    name: "Ali Baba",
    image: require("../assets/images/resto.jpg"),
    description: "Authentic Middle Eastern and North African dishes.",
    rating: 4.5,
    address: "15 Independence Drive, Serrekunda",
    categories: ["Middle Eastern", "North African"],
    openingHours: "12:00 PM - 11:00 PM",
    reviewsCount: 110,
    freeDelivery: false,
  },
  {
    id: 3,
    name: "Sally's Kitchen",
    image: require("../assets/images/resto.jpg"),
    description: "Homestyle Gambian food with fresh local ingredients.",
    rating: 4.7,
    address: "Serrekunda Central Market",
    categories: ["Gambian", "Local"],
    openingHours: "8:00 AM - 8:00 PM",
    reviewsCount: 130,
    freeDelivery: true,
  },
  {
    id: 4,
    name: "King Baker",
    image: require("../assets/images/resto.jpg"),
    description: "Famous bakery and café offering fresh pastries and meals.",
    rating: 4.8,
    address: "Bakau New Town, Bakau",
    categories: ["Bakery", "Cafe"],
    openingHours: "7:00 AM - 9:00 PM",
    reviewsCount: 150,
    freeDelivery: false,
  },
  {
    id: 5,
    name: "Plasta Inc",
    image: require("../assets/images/resto.jpg"),
    description:
      "Modern fusion cuisine blending African and international flavors.",
    rating: 4.4,
    address: "Tanji Fishing Village, Kombo South",
    categories: ["Fusion", "African"],
    openingHours: "11:00 AM - 10:00 PM",
    reviewsCount: 90,
    freeDelivery: true,
  },
  {
    id: 6,
    name: "Chop Shop",
    image: require("../assets/images/resto.jpg"),
    description: "Barbecue and grilled dishes, popular for casual dining.",
    rating: 4.3,
    address: "Serekunda Mall, Serekunda",
    categories: ["Barbecue", "Casual"],
    openingHours: "12:00 PM - 11:00 PM",
    reviewsCount: 95,
    freeDelivery: false,
  },
  {
    id: 7,
    name: "Gusto Restaurant",
    image: require("../assets/images/resto.jpg"),
    description: "Upscale dining with a mix of local and international dishes.",
    rating: 4.7,
    address: "Fajara, Bakau",
    categories: ["Upscale", "International"],
    openingHours: "11:00 AM - 11:00 PM",
    reviewsCount: 110,
    freeDelivery: true,
  },
  {
    id: 8,
    name: "Cassy's Restaurant",
    image: require("../assets/images/resto.jpg"),
    description: "Casual dining with a focus on fresh seafood.",
    rating: 4.5,
    address: "Bakau Central, Bakau",
    categories: ["Seafood", "Casual"],
    openingHours: "10:00 AM - 10:00 PM",
    reviewsCount: 85,
    freeDelivery: false,
  },
  {
    id: 9,
    name: "Reo's Bar & Restaurant",
    image: require("../assets/images/resto.jpg"),
    description: "Lively spot offering drinks, local dishes, and live music.",
    rating: 4.2,
    address: "Senegambia, Kololi",
    categories: ["Bar", "Local"],
    openingHours: "4:00 PM - 12:00 AM",
    reviewsCount: 100,
    freeDelivery: true,
  },
  {
    id: 10,
    name: "Heritage Restaurant",
    image: require("../assets/images/resto.jpg"),
    description: "Traditional Gambian cuisine served in an elegant setting.",
    rating: 4.6,
    address: "Banjul City Center",
    categories: ["Gambian", "Traditional"],
    openingHours: "10:00 AM - 10:00 PM",
    reviewsCount: 120,
    freeDelivery: false,
  },
];

export const stores = [
  {
    id: 1,
    name: "SeneGambia ",
    image: require("../assets/images/bev.jpg"),
    description: "Wide range of groceries and household items.",
    rating: 4.5,
    address: "Senegambia Road, Kololi",
    categories: ["Groceries", "Household"],
    openingHours: "8:00 AM - 9:00 PM",
    reviewsCount: 140,
  },
  {
    id: 2,
    name: "Kairaba",
    image: require("../assets/images/bev.jpg"),
    description: "Local grocery store with fresh produce and staples.",
    rating: 4.3,
    address: "Kairaba Avenue, Banjul",
    categories: ["Groceries", "Fresh Produce"],
    openingHours: "7:00 AM - 8:00 PM",
    reviewsCount: 95,
  },
  {
    id: 3,
    name: "Tuba Store",
    image: require("../assets/images/bev.jpg"),
    description: "Convenience store offering snacks, drinks, and essentials.",
    rating: 4.0,
    address: "Serekunda Central Market",
    categories: ["Convenience", "Snacks"],
    openingHours: "6:00 AM - 10:00 PM",
    reviewsCount: 80,
  },
  {
    id: 4,
    name: "Brikama ",
    image: require("../assets/images/bev.jpg"),
    description: "Hardware and construction materials supplier.",
    rating: 4.2,
    address: "Brikama Main Road",
    categories: ["Hardware", "Construction"],
    openingHours: "8:00 AM - 6:00 PM",
    reviewsCount: 70,
  },
  {
    id: 5,
    name: "Mansa Store",
    image: require("../assets/images/bev.jpg"),
    description: "General store with household goods and groceries.",
    rating: 4.1,
    address: "Mansa Konko",
    categories: ["Groceries", "Household"],
    openingHours: "7:00 AM - 9:00 PM",
    reviewsCount: 65,
  },
  {
    id: 6,
    name: "Gambia Mall",
    image: require("../assets/images/bev.jpg"),
    description: "Modern supermarket with a wide variety of products.",
    rating: 4.6,
    address: "Kotu Beach Road",
    categories: ["Groceries", "Electronics"],
    openingHours: "8:00 AM - 10:00 PM",
    reviewsCount: 150,
  },
  {
    id: 7,
    name: "Bakau Market",
    image: require("../assets/images/bev.jpg"),
    description: "Fresh fruits, vegetables, and local produce market.",
    rating: 4.4,
    address: "Bakau Central",
    categories: ["Fresh Produce", "Fruits & Vegetables"],
    openingHours: "6:00 AM - 6:00 PM",
    reviewsCount: 100,
  },
  {
    id: 8,
    name: "Tanji Fish",
    image: require("../assets/images/bev.jpg"),
    description: "Fresh seafood and fish directly from the coast.",
    rating: 4.7,
    address: "Tanji Fishing Village",
    categories: ["Seafood", "Fresh Fish"],
    openingHours: "5:00 AM - 5:00 PM",
    reviewsCount: 110,
  },
  {
    id: 9,
    name: "Kololi Store",
    image: require("../assets/images/bev.jpg"),
    description: "Convenience store for snacks, drinks, and essentials.",
    rating: 4.1,
    address: "Kololi Main Street",
    categories: ["Convenience", "Snacks"],
    openingHours: "7:00 AM - 11:00 PM",
    reviewsCount: 90,
  },
  {
    id: 10,
    name: "Serekunda Electronics",
    image: require("../assets/images/bev.jpg"),
    description: "Electronic gadgets, appliances, and accessories.",
    rating: 4.3,
    address: "Serekunda Mall",
    categories: ["Electronics", "Appliances"],
    openingHours: "9:00 AM - 8:00 PM",
    reviewsCount: 75,
  },
];

export const topPicks = [
  {
    id: 1,
    name: "Chicken Yassa",
    image: require("../assets/images/pizza.jpg"),
    description: "Grilled chicken in onion lemon sauce",
    price: 250,
    rating: 4.8,
    tags: ["Spicy", "Local Favorite"],
    reviewsCount: 87,
    storeId: 1,
    storeName: "SeneGambia ",
  },
  {
    id: 2,
    name: "Beef Domoda",
    image: require("../assets/images/pizza.jpg"),
    description: "Peanut stew with tender beef and rice",
    price: 220,
    rating: 4.7,
    tags: ["Rich Flavor", "Popular"],
    reviewsCount: 74,
    storeId: 2,
    storeName: "Kairaba",
  },
  {
    id: 3,
    name: "Shawarma Wrap",
    image: require("../assets/images/pizza.jpg"),
    description: "Juicy meat wrap with garlic sauce",
    price: 180,
    rating: 4.6,
    tags: ["Fast Bite", "Halal"],
    reviewsCount: 102,
    storeId: 1,
    storeName: "SeneGambia",
  },
  {
    id: 4,
    name: "Jollof Rice & Chicken",
    image: require("../assets/images/pizza.jpg"),
    description: "Classic West African jollof rice with grilled chicken",
    price: 200,
    rating: 4.9,
    tags: ["West African", "Best Seller"],
    reviewsCount: 132,
    storeId: 4,
    storeName: "Brikama ",
  },
  {
    id: 5,
    name: "Pizza Margherita",
    image: require("../assets/images/pizza.jpg"),
    description: "Cheesy tomato pizza with herbs",
    price: 280,
    rating: 4.5,
    tags: ["Vegetarian", "Italian"],
    reviewsCount: 65,
    storeId: 5,
    storeName: "Mansa Store",
  },
  {
    id: 6,
    name: "Fish Benechin",
    image: require("../assets/images/pizza.jpg"),
    description: "Senegalese-style one-pot rice and fish",
    price: 230,
    rating: 4.7,
    tags: ["Traditional", "Healthy"],
    reviewsCount: 89,
    storeId: 6,
    storeName: "Gambia Mall",
  },
];

// Carrefour-style Home Page Sections Data
export const heroBanners = [
  {
    id: 1,
    title: "Fresh Groceries Delivered",
    subtitle: "Same day delivery available",
    image: require("../assets/images/hero-grocery.jpg"),
    backgroundColor: "#ff6b00",
    textColor: "#fff",
  },
  {
    id: 2,
    title: "Tech Deals Up to 50% Off",
    subtitle: "Limited time offers",
    image: require("../assets/images/hero-grocery.jpg"),
    backgroundColor: "#2C5AA0",
    textColor: "#fff",
  },
  {
    id: 3,
    title: "Fresh from Local Farms",
    subtitle: "Organic produce daily",
    image: require("../assets/images/hero-grocery.jpg"),
    backgroundColor: "#27AE60",
    textColor: "#fff",
  },
];

export const snackingCornerProducts = [
  {
    id: 1,
    name: "Pringles Original",
    price: 25.0,
    originalPrice: 30.0,
    image: require("../assets/images/product.jpg"),
    category: "Snacks",
    inStock: true,
    quantity: 0,
  },
  {
    id: 2,
    name: "Coca Cola 350ml",
    price: 15.0,
    image: require("../assets/images/product.jpg"),
    category: "Beverages",
    inStock: true,
    quantity: 0,
  },
  {
    id: 3,
    name: "Kit Kat Chocolate",
    price: 20.0,
    originalPrice: 25.0,
    image: require("../assets/images/product.jpg"),
    category: "Sweets",
    inStock: true,
    quantity: 0,
  },
  {
    id: 4,
    name: "Lay's Chips",
    price: 18.0,
    image: require("../assets/images/product.jpg"),
    category: "Snacks",
    inStock: true,
    quantity: 0,
  },
  {
    id: 5,
    name: "Pepsi 350ml",
    price: 15.0,
    image: require("../assets/images/product.jpg"),
    category: "Beverages",
    inStock: false,
    quantity: 0,
  },
  {
    id: 6,
    name: "Oreo Cookies",
    price: 22.0,
    image: require("../assets/images/product.jpg"),
    category: "Sweets",
    inStock: true,
    quantity: 0,
  },
];

export const gadgetTechProducts = [
  {
    id: 1,
    name: "Samsung Galaxy Earbuds",
    price: 1250.0,
    originalPrice: 1500.0,
    image: require("../assets/images/product.jpg"),
    category: "Audio",
    inStock: true,
    quantity: 0,
    rating: 4.5,
  },
  {
    id: 2,
    name: "iPhone Charger Cable",
    price: 150.0,
    image: require("../assets/images/product.jpg"),
    category: "Accessories",
    inStock: true,
    quantity: 0,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    price: 800.0,
    originalPrice: 1000.0,
    image: require("../assets/images/product.jpg"),
    category: "Audio",
    inStock: true,
    quantity: 0,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Power Bank 10000mAh",
    price: 450.0,
    image: require("../assets/images/product.jpg"),
    category: "Power",
    inStock: true,
    quantity: 0,
    rating: 4.3,
  },
  {
    id: 5,
    name: "Wireless Mouse",
    price: 280.0,
    originalPrice: 350.0,
    image: require("../assets/images/product.jpg"),
    category: "Computer",
    inStock: true,
    quantity: 0,
    rating: 4.4,
  },
];

export const dealsData = [
  {
    id: 1,
    title: "Weekend Super Sale",
    subtitle: "Up to 70% off on Electronics",
    image: require("../assets/images/hero-grocery.jpg"),
    discount: "70%",
    backgroundColor: "#E74C3C",
  },
  {
    id: 2,
    title: "Fresh Produce Special",
    subtitle: "Buy 2 Get 1 Free on Fruits",
    image: require("../assets/images/hero-grocery.jpg"),
    discount: "Buy 2 Get 1",
    backgroundColor: "#27AE60",
  },
  {
    id: 3,
    title: "Home Essentials",
    subtitle: "Save big on household items",
    image: require("../assets/images/hero-grocery.jpg"),
    discount: "50%",
    backgroundColor: "#8E44AD",
  },
];

export const freshFromFarmProducts = [
  {
    id: 1,
    name: "Organic Tomatoes",
    price: 35.0,
    unit: "per kg",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Vegetables",
    inStock: true,
    quantity: 0,
    organic: true,
    freshness: "Picked Today",
  },
  {
    id: 2,
    name: "Fresh Bananas",
    price: 20.0,
    unit: "per bunch",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Fruits",
    inStock: true,
    quantity: 0,
    organic: false,
    freshness: "Farm Fresh",
  },
  {
    id: 3,
    name: "Organic Spinach",
    price: 40.0,
    unit: "per bunch",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Leafy Greens",
    inStock: true,
    quantity: 0,
    organic: true,
    freshness: "Just Harvested",
  },
  {
    id: 4,
    name: "Red Apples",
    price: 60.0,
    unit: "per kg",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Fruits",
    inStock: true,
    quantity: 0,
    organic: false,
    freshness: "Premium Quality",
  },
  {
    id: 5,
    name: "Organic Carrots",
    price: 25.0,
    unit: "per kg",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Vegetables",
    inStock: true,
    quantity: 0,
    organic: true,
    freshness: "Garden Fresh",
  },
  {
    id: 6,
    name: "Sweet Oranges",
    price: 45.0,
    unit: "per kg",
    image: require("../assets/images/hero-grocery.jpg"),
    category: "Fruits",
    inStock: true,
    quantity: 0,
    organic: false,
    freshness: "Sweet & Juicy",
  },
];

export const popularStoresData = [
  {
    id: 1,
    name: "FreshMart Supermarket",
    image: require("../assets/images/hero-grocery.jpg"),
    rating: 4.6,
    deliveryTime: "20-30 min",
    deliveryFee: "Free delivery",
    categories: ["Groceries", "Fresh Produce", "Household"],
    discount: "20% off first order",
  },
  {
    id: 2,
    name: "TechHub Electronics",
    image: require("../assets/images/hero-grocery.jpg"),
    rating: 4.4,
    deliveryTime: "45-60 min",
    deliveryFee: "D25 delivery",
    categories: ["Electronics", "Gadgets", "Accessories"],
    discount: "Free shipping over D500",
  },
  {
    id: 3,
    name: "Green Valley Organics",
    image: require("../assets/images/hero-grocery.jpg"),
    rating: 4.8,
    deliveryTime: "30-45 min",
    deliveryFee: "Free delivery",
    categories: ["Organic", "Fresh", "Healthy"],
    discount: "15% off organic items",
  },
  {
    id: 4,
    name: "Quick Bites Corner",
    image: require("../assets/images/hero-grocery.jpg"),
    rating: 4.2,
    deliveryTime: "15-25 min",
    deliveryFee: "D15 delivery",
    categories: ["Snacks", "Beverages", "Quick Meals"],
    discount: "Buy 3 Get 1 Free",
  },
];

// Great for Breakfast - Gambian Morning Favorites
export const greatForBreakfastProducts = [
  {
    id: 1,
    name: "Tapalapa Bread",
    price: 10.0,
    image: require("../assets/images/product.jpg"),
    category: "Bread",
    inStock: true,
    quantity: 0,
    description: "Fresh local bread, perfect for breakfast",
    popular: true,
    storeId: 1,
    storeName: "Local Bakery",
  },
  {
    id: 2,
    name: "Café Touba Coffee",
    price: 25.0,
    image: require("../assets/images/product.jpg"),
    category: "Beverages",
    inStock: true,
    quantity: 0,
    description: "Traditional spiced coffee",
    popular: true,
    storeId: 2,
    storeName: "Café Corner",
  },
  {
    id: 3,
    name: "Porridge Mix",
    price: 35.0,
    image: require("../assets/images/product.jpg"),
    category: "Cereals",
    inStock: true,
    quantity: 0,
    description: "Millet and corn porridge mix",
    healthy: true,
    storeId: 1,
    storeName: "Local Bakery",
  },
  {
    id: 4,
    name: "Honey (Local)",
    price: 80.0,
    unit: "per jar",
    image: require("../assets/images/product.jpg"),
    category: "Natural",
    inStock: true,
    quantity: 0,
    description: "Pure local honey from Gambian bees",
    organic: true,
    storeId: 3,
    storeName: "Natural Market",
  },
  {
    id: 5,
    name: "Groundnut Butter",
    price: 45.0,
    image: require("../assets/images/product.jpg"),
    category: "Spreads",
    inStock: true,
    quantity: 0,
    description: "Homemade groundnut butter",
    local: true,
    storeId: 1,
    storeName: "Local Bakery",
  },
  {
    id: 6,
    name: "Fresh Milk (Local)",
    price: 30.0,
    unit: "per liter",
    image: require("../assets/images/product.jpg"),
    category: "Dairy",
    inStock: true,
    quantity: 0,
    description: "Fresh cow milk from local farms",
    fresh: true,
    storeId: 4,
    storeName: "Dairy Farm",
  },
];

// Traditional Gambian Meals
export const traditionalMealsProducts = [
  {
    id: 1,
    name: "Benachin Rice",
    price: 45.0,
    unit: "per serving",
    image: require("../assets/images/product.jpg"),
    category: "Main Course",
    inStock: true,
    quantity: 0,
    description: "One-pot rice dish with vegetables and meat",
    traditional: true,
    spiceLevel: "Medium",
    storeId: 5,
    storeName: "Traditional Kitchen",
  },
  {
    id: 2,
    name: "Domoda Sauce",
    price: 40.0,
    unit: "per portion",
    image: require("../assets/images/product.jpg"),
    category: "Sauces",
    inStock: true,
    quantity: 0,
    description: "Groundnut stew with meat and vegetables",
    traditional: true,
    spiceLevel: "Mild",
    storeId: 5,
    storeName: "Traditional Kitchen",
  },
  {
    id: 3,
    name: "Yassa Chicken",
    price: 60.0,
    unit: "per serving",
    image: require("../assets/images/product.jpg"),
    category: "Main Course",
    inStock: true,
    quantity: 0,
    description: "Marinated chicken in onion and lemon sauce",
    traditional: true,
    spiceLevel: "Spicy",
    storeId: 5,
    storeName: "Traditional Kitchen",
  },
  {
    id: 4,
    name: "Plasas (Spinach Stew)",
    price: 35.0,
    unit: "per serving",
    image: require("../assets/images/product.jpg"),
    category: "Vegetarian",
    inStock: true,
    quantity: 0,
    description: "Traditional spinach stew with groundnuts",
    healthy: true,
    vegetarian: true,
    storeId: 6,
    storeName: "Healthy Greens",
  },
  {
    id: 5,
    name: "Chere (Couscous)",
    price: 25.0,
    unit: "per serving",
    image: require("../assets/images/product.jpg"),
    category: "Grains",
    inStock: true,
    quantity: 0,
    description: "Steamed millet couscous",
    traditional: true,
    healthy: true,
    storeId: 5,
    storeName: "Traditional Kitchen",
  },
  {
    id: 6,
    name: "Fish Supakanja",
    price: 55.0,
    unit: "per serving",
    image: require("../assets/images/product.jpg"),
    category: "Seafood",
    inStock: true,
    quantity: 0,
    description: "Okra stew with fresh fish",
    traditional: true,
    fresh: true,
    storeId: 7,
    storeName: "Seaside Kitchen",
  },
];

// Local Beverages & Drinks
export const localBeveragesProducts = [
  {
    id: 1,
    name: "Bissap (Hibiscus Tea)",
    price: 15.0,
    image: require("../assets/images/product.jpg"),
    category: "Traditional Drinks",
    inStock: true,
    quantity: 0,
    description: "Refreshing hibiscus flower tea",
    healthy: true,
    refreshing: true,
    storeId: 8,
    storeName: "Refreshing Drinks",
  },
  {
    id: 2,
    name: "Baobab Juice",
    price: 20.0,
    image: require("../assets/images/product.jpg"),
    category: "Natural Juices",
    inStock: true,
    quantity: 0,
    description: "Vitamin-rich baobab fruit juice",
    healthy: true,
    vitaminC: true,
  },
  {
    id: 3,
    name: "Ginger Beer (Local)",
    price: 18.0,
    image: require("../assets/images/product.jpg"),
    category: "Soft Drinks",
    inStock: true,
    quantity: 0,
    description: "Spicy homemade ginger beer",
    local: true,
    spicy: true,
  },
  {
    id: 4,
    name: "Palm Wine",
    price: 35.0,
    image: require("../assets/images/product.jpg"),
    category: "Traditional",
    inStock: true,
    quantity: 0,
    description: "Fresh palm wine from local palms",
    traditional: true,
    adult: true,
  },
  {
    id: 5,
    name: "Wonjo Drink",
    price: 12.0,
    image: require("../assets/images/product.jpg"),
    category: "Traditional Drinks",
    inStock: true,
    quantity: 0,
    description: "Traditional sorrel drink",
    refreshing: true,
    cooling: true,
  },
];

// TeranGo Picks - Curated selections
export const terangoPicksProducts = [
  {
    id: 1,
    name: "Attaya Tea Set",
    price: 120.0,
    originalPrice: 150.0,
    image: require("../assets/images/product.jpg"),
    category: "Traditional",
    inStock: true,
    quantity: 0,
    description: "Complete traditional tea set for authentic Gambian attaya",
    popular: true,
    local: true,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Kankurang Mask Art",
    price: 250.0,
    image: require("../assets/images/product.jpg"),
    category: "Arts & Crafts",
    inStock: true,
    quantity: 0,
    description: "Handcrafted traditional Kankurang mask",
    local: true,
    traditional: true,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Gambian Honey Bundle",
    price: 180.0,
    originalPrice: 220.0,
    image: require("../assets/images/product.jpg"),
    category: "Natural Products",
    inStock: true,
    quantity: 0,
    description: "Pure honey from local Gambian beekeepers",
    organic: true,
    healthy: true,
    local: true,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Djembe Drum",
    price: 450.0,
    image: require("../assets/images/product.jpg"),
    category: "Music",
    inStock: true,
    quantity: 0,
    description: "Authentic West African djembe drum",
    traditional: true,
    local: true,
    rating: 4.9,
  },
  {
    id: 5,
    name: "Baobab Fruit Pack",
    price: 65.0,
    image: require("../assets/images/product.jpg"),
    category: "Superfoods",
    inStock: true,
    quantity: 0,
    description: "Vitamin-rich baobab fruit powder",
    healthy: true,
    organic: true,
    vitaminC: true,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Kente Cloth Fashion",
    price: 320.0,
    originalPrice: 400.0,
    image: require("../assets/images/product.jpg"),
    category: "Fashion",
    inStock: true,
    quantity: 0,
    description: "Beautiful traditional Kente cloth designs",
    traditional: true,
    popular: true,
    rating: 4.8,
  },
];

// Trending Now - Popular items
export const trendingNowProducts = [
  {
    id: 1,
    name: "Solar Power Bank",
    price: 180.0,
    originalPrice: 220.0,
    image: require("../assets/images/product.jpg"),
    category: "Tech",
    inStock: true,
    quantity: 0,
    description: "Eco-friendly solar charging solution",
    popular: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Moringa Powder",
    price: 45.0,
    image: require("../assets/images/product.jpg"),
    category: "Health",
    inStock: true,
    quantity: 0,
    description: "Nutrient-rich moringa superfood powder",
    healthy: true,
    organic: true,
    local: true,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Mosquito Net Bundle",
    price: 85.0,
    originalPrice: 100.0,
    image: require("../assets/images/product.jpg"),
    category: "Home & Health",
    inStock: true,
    quantity: 0,
    description: "Long-lasting insecticide-treated nets",
    popular: true,
    rating: 4.6,
  },
  {
    id: 4,
    name: "Traditional Drums Set",
    price: 280.0,
    image: require("../assets/images/product.jpg"),
    category: "Music",
    inStock: true,
    quantity: 0,
    description: "Collection of traditional percussion instruments",
    traditional: true,
    local: true,
    rating: 4.8,
  },
  {
    id: 5,
    name: "Shea Butter Collection",
    price: 120.0,
    image: require("../assets/images/product.jpg"),
    category: "Beauty",
    inStock: true,
    quantity: 0,
    description: "Pure, unrefined shea butter products",
    organic: true,
    healthy: true,
    local: true,
    rating: 4.9,
  },
];

// Weekly Deals - Special offers
export const weeklyDealsProducts = [
  {
    id: 1,
    name: "Rice 50kg Bag",
    price: 180.0,
    originalPrice: 220.0,
    image: require("../assets/images/product.jpg"),
    category: "Staples",
    inStock: true,
    quantity: 0,
    description: "Premium quality imported rice",
    unit: "per 50kg bag",
    popular: true,
  },
  {
    id: 2,
    name: "Cooking Oil 5L",
    price: 85.0,
    originalPrice: 100.0,
    image: require("../assets/images/product.jpg"),
    category: "Cooking",
    inStock: true,
    quantity: 0,
    description: "Pure vegetable cooking oil",
    unit: "per 5L bottle",
  },
  {
    id: 3,
    name: "Sugar 2kg Pack",
    price: 45.0,
    originalPrice: 55.0,
    image: require("../assets/images/product.jpg"),
    category: "Staples",
    inStock: true,
    quantity: 0,
    description: "Refined white sugar",
    unit: "per 2kg pack",
  },
  {
    id: 4,
    name: "Milk Powder 400g",
    price: 120.0,
    originalPrice: 140.0,
    image: require("../assets/images/product.jpg"),
    category: "Dairy",
    inStock: true,
    quantity: 0,
    description: "Full cream milk powder",
    unit: "per 400g tin",
  },
];
