name: terango-web-app
static_sites:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  envs:
  - key: EXPO_PUBLIC_API_URL
    value: https://monkfish-app-korrv.ondigitalocean.app
    type: GENERAL
  - key: NODE_ENV
    value: production
    type: GENERAL